"""add survey ignored repo

Revision ID: 18e55c2cb255
Revises: b7e4c1a9d2f0
Create Date: 2026-10-10 14:48:31.524038
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18e55c2cb255'
down_revision: Union[str, None] = 'b7e4c1a9d2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """新增已忽略仓库表。已有巡检没有任何已忽略仓库，无需回填。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_ignored_repo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('repo_slug', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_ignored_repo', schema=None) as batch_op:
        batch_op.create_index('ux_survey_ignored_repo', ['survey_id', 'repo_slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """删除已忽略仓库表。被忽略的仓库下一轮起重新参与巡检，台账里已标为已忽略的行停在原状态。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_ignored_repo', schema=None) as batch_op:
        batch_op.drop_index('ux_survey_ignored_repo')

    op.drop_table('survey_ignored_repo')
    # ### end Alembic commands ###
