"""add survey ledger, bindings and pushes

Revision ID: 1a00c8f2781a
Revises: 737cc79457ad
Create Date: 2026-09-13 21:24:05.066648
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1a00c8f2781a'
down_revision: Union[str, None] = '737cc79457ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_binding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('last_succeeded_push_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_binding', schema=None) as batch_op:
        batch_op.create_index('ix_survey_binding_survey', ['survey_id'], unique=False)

    op.create_table('survey_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('repo_slug', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('lines', sa.Text(), nullable=True),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_uid', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_ledger', schema=None) as batch_op:
        batch_op.create_index('ux_survey_ledger', ['survey_id', 'fingerprint'], unique=True)

    op.create_table('survey_push',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('binding_id', sa.Integer(), nullable=True),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stats', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['binding_id'], ['survey_binding.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['survey_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_push', schema=None) as batch_op:
        batch_op.create_index('ix_survey_push_binding_status', ['binding_id', 'status'], unique=False)
        batch_op.create_index('ix_survey_push_run', ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_push', schema=None) as batch_op:
        batch_op.drop_index('ix_survey_push_run')
        batch_op.drop_index('ix_survey_push_binding_status')

    op.drop_table('survey_push')
    with op.batch_alter_table('survey_ledger', schema=None) as batch_op:
        batch_op.drop_index('ux_survey_ledger')

    op.drop_table('survey_ledger')
    with op.batch_alter_table('survey_binding', schema=None) as batch_op:
        batch_op.drop_index('ix_survey_binding_survey')

    op.drop_table('survey_binding')
    # ### end Alembic commands ###
