"""add survey run repo reach

Revision ID: 38cafc1d3180
Revises: fd5e9dedca82
Create Date: 2026-10-09 15:55:42.644619
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '38cafc1d3180'
down_revision: Union[str, None] = 'fd5e9dedca82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """新增 survey_run_repo.reach。已有的行保持 NULL，界面显示为无记录。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_run_repo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reach', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """删除 survey_run_repo.reach。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_run_repo', schema=None) as batch_op:
        batch_op.drop_column('reach')

    # ### end Alembic commands ###
