"""add survey tables

Revision ID: 737cc79457ad
Revises: 64db99aae2b1
Create Date: 2026-09-09 07:20:56.822855
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '737cc79457ad'
down_revision: Union[str, None] = '64db99aae2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('schedule_kind', sa.String(length=16), nullable=False),
    sa.Column('schedule_expr', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('excluded_skills', sa.Text(), nullable=True),
    sa.Column('delete_workspace_after', sa.Integer(), nullable=False),
    sa.Column('budget_wall_clock_minutes', sa.Integer(), nullable=True),
    sa.Column('budget_l1_max_chars', sa.Integer(), nullable=True),
    sa.Column('budget_l2_max_focus', sa.Integer(), nullable=True),
    sa.Column('budget_index_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('retention_runs', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('survey_uid')
    )
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.create_index('ix_survey_next_run', ['enabled', 'next_run_at'], unique=False)

    op.create_table('survey_ignore',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_ignore', schema=None) as batch_op:
        batch_op.create_index('ux_survey_ignore', ['survey_id', 'fingerprint'], unique=True)

    op.create_table('survey_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_uid', sa.String(length=36), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=True),
    sa.Column('repos_total', sa.Integer(), nullable=False),
    sa.Column('repos_done', sa.Integer(), nullable=False),
    sa.Column('matched_skills', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('degradations', sa.Text(), nullable=True),
    sa.Column('error_kind', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_uid')
    )
    with op.batch_alter_table('survey_run', schema=None) as batch_op:
        batch_op.create_index('ix_survey_run_status_heartbeat', ['status', 'heartbeat_at'], unique=False)
        batch_op.create_index('ix_survey_run_survey_started', ['survey_id', 'started_at'], unique=False)

    op.create_table('survey_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('exclude_patterns', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_source', schema=None) as batch_op:
        batch_op.create_index('ix_survey_source_survey', ['survey_id'], unique=False)

    op.create_table('survey_finding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('repo_slug', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['survey_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_finding', schema=None) as batch_op:
        batch_op.create_index('ix_survey_finding_run', ['run_id'], unique=False)
        batch_op.create_index('ix_survey_finding_survey_created', ['survey_id', 'created_at'], unique=False)
        batch_op.create_index('ix_survey_finding_survey_fp', ['survey_id', 'fingerprint'], unique=False)

    op.create_table('survey_run_repo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('repo_slug', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('profile_kind', sa.String(length=24), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['survey_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_run_repo', schema=None) as batch_op:
        batch_op.create_index('ix_survey_run_repo_run', ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_run_repo', schema=None) as batch_op:
        batch_op.drop_index('ix_survey_run_repo_run')

    op.drop_table('survey_run_repo')
    with op.batch_alter_table('survey_finding', schema=None) as batch_op:
        batch_op.drop_index('ix_survey_finding_survey_fp')
        batch_op.drop_index('ix_survey_finding_survey_created')
        batch_op.drop_index('ix_survey_finding_run')

    op.drop_table('survey_finding')
    with op.batch_alter_table('survey_source', schema=None) as batch_op:
        batch_op.drop_index('ix_survey_source_survey')

    op.drop_table('survey_source')
    with op.batch_alter_table('survey_run', schema=None) as batch_op:
        batch_op.drop_index('ix_survey_run_survey_started')
        batch_op.drop_index('ix_survey_run_status_heartbeat')

    op.drop_table('survey_run')
    with op.batch_alter_table('survey_ignore', schema=None) as batch_op:
        batch_op.drop_index('ux_survey_ignore')

    op.drop_table('survey_ignore')
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_index('ix_survey_next_run')

    op.drop_table('survey')
    # ### end Alembic commands ###
