"""initial schema

Revision ID: 8fb535a77556
Revises: 
Create Date: 2026-09-05 16:27:34.761227
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8fb535a77556'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leader_lease',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('holder', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('mr_settlement',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('mr_iid', sa.Integer(), nullable=False),
    sa.Column('mr_state', sa.String(length=16), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id', 'mr_iid')
    )
    op.create_table('review_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_uid', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_path', sa.String(length=512), nullable=True),
    sa.Column('mr_iid', sa.Integer(), nullable=False),
    sa.Column('mr_title', sa.Text(), nullable=True),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('review_mode', sa.String(length=16), nullable=False),
    sa.Column('review_skills', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('phase', sa.String(length=32), nullable=True),
    sa.Column('files_total', sa.Integer(), nullable=False),
    sa.Column('files_done', sa.Integer(), nullable=False),
    sa.Column('degradations', sa.Text(), nullable=True),
    sa.Column('error_kind', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_uid')
    )
    with op.batch_alter_table('review_run', schema=None) as batch_op:
        batch_op.create_index('ix_review_run_mr', ['project_id', 'mr_iid'], unique=False)
        batch_op.create_index('ix_review_run_started_at', ['started_at'], unique=False)
        batch_op.create_index('ix_review_run_status_heartbeat', ['status', 'heartbeat_at'], unique=False)

    op.create_table('finding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('mr_iid', sa.Integer(), nullable=False),
    sa.Column('discussion_id', sa.String(length=128), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('delivery', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('verdict_reason', sa.String(length=32), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['review_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.create_index('ix_finding_mr_verdict', ['project_id', 'mr_iid', 'verdict'], unique=False)
        batch_op.create_index('ix_finding_run', ['run_id'], unique=False)
        batch_op.create_index('ux_finding_discussion', ['project_id', 'discussion_id'], unique=True, sqlite_where=sa.text('discussion_id IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index('ux_finding_discussion', sqlite_where=sa.text('discussion_id IS NOT NULL'))
        batch_op.drop_index('ix_finding_run')
        batch_op.drop_index('ix_finding_mr_verdict')

    op.drop_table('finding')
    with op.batch_alter_table('review_run', schema=None) as batch_op:
        batch_op.drop_index('ix_review_run_status_heartbeat')
        batch_op.drop_index('ix_review_run_started_at')
        batch_op.drop_index('ix_review_run_mr')

    op.drop_table('review_run')
    op.drop_table('mr_settlement')
    op.drop_table('leader_lease')
    # ### end Alembic commands ###
