"""add app_setting

Revision ID: a83e6e396079
Revises: 8fb535a77556
Create Date: 2026-09-06 01:08:22.984363
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a83e6e396079'
down_revision: Union[str, None] = '8fb535a77556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_setting')
    # ### end Alembic commands ###
