"""add codegraph insight columns

Revision ID: d2a3378d6cb3
Revises: 38cafc1d3180
Create Date: 2026-10-09 12:03:20.383180
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd2a3378d6cb3'
down_revision: Union[str, None] = '38cafc1d3180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """新增 codegraph 执行情况与线索来源的列；全部可空，旧数据为 NULL 表示"无记录"。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_finding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clue_source', sa.String(length=16), nullable=True))

    with op.batch_alter_table('survey_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codegraph_stats', sa.Text(), nullable=True))

    with op.batch_alter_table('survey_run_repo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index_mode', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('index_ms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('route_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """删除上述列。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_run_repo', schema=None) as batch_op:
        batch_op.drop_column('type_count')
        batch_op.drop_column('route_count')
        batch_op.drop_column('index_ms')
        batch_op.drop_column('index_mode')

    with op.batch_alter_table('survey_run', schema=None) as batch_op:
        batch_op.drop_column('codegraph_stats')

    with op.batch_alter_table('survey_finding', schema=None) as batch_op:
        batch_op.drop_column('clue_source')

    # ### end Alembic commands ###
