"""add survey recheck tracking

Revision ID: fd5e9dedca82
Revises: 1a00c8f2781a
Create Date: 2026-10-09 15:20:07.826916
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd5e9dedca82'
down_revision: Union[str, None] = '1a00c8f2781a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """新增复核所需的两列。已有的行保持 NULL：旧运行沿用朴素差集，旧台账行视为从未复核、优先轮到。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_checked_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('survey_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inspected_files', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """删除复核所需的两列。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_run', schema=None) as batch_op:
        batch_op.drop_column('inspected_files')

    with op.batch_alter_table('survey_ledger', schema=None) as batch_op:
        batch_op.drop_column('last_checked_at')

    # ### end Alembic commands ###
